server:
  port: 8080

spring:
  application:
    name: investment_system
  datasource:
    url: jdbc:postgresql://localhost:5432/investment_system_db
    username: mike
    password: password
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      dialect: org.hibernate.dialect.PostgreSQLDialect
      show-sql: true


